Repository mazipan/baca-quran.id, pull requests merged in 2024-10, with the labels that each got.

#279 feat: use contrib.rocks to lists all contributors
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#281 refactor: remove unused links
  README.md
  static/README.md
Labels: automerge, hacktoberfest, hacktoberfest-accepted

#284 CI: Add check build
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
Labels: hacktoberfest, hacktoberfest-accepted

#285 FEAT: Grayscale past prayer
  package.json
  pnpm-lock.yaml
  src/lib/PrayerTimeCard.svelte
  src/lib/PrayerTimeList.svelte
  src/lib/types.ts
  src/routes/jadwal-sholat/+page.svelte
  static/README.md
Labels: enhancement, automerge, hacktoberfest, hacktoberfest-accepted

#289 FEAT: MVP for recap log prayer
  .github/workflows/ci.yml
  scripts/routes.js
  src/lib/CardShadow.svelte
  src/lib/PrayerTimeCard.svelte
  src/lib/PrayerTimeList.svelte
  src/lib/ThemeSwicther.svelte
  src/lib/constants.ts
  src/lib/types.ts
  src/lib/utils/array.ts
  src/lib/utils/date.ts
  src/routes/+layout.svelte
  src/routes/jadwal-sholat/+page.svelte
  src/routes/pencatat-ibadah/+page.svelte
  src/routes/pencatat-ibadah/rekap/+page.svelte
  src/routes/sync/+page.svelte
  tailwind.config.js
Labels: automerge, hacktoberfest, hacktoberfest-accepted

#290 CI: build ci
  .github/workflows/ci.yml
  README.md
  package.json
  static/README.md
Labels: automerge, hacktoberfest, hacktoberfest-accepted
